### ISSUE TITLE
No module named 'openmixup'

### ISSUE THREAD

**Issue by xiangyu8** [Westlake-AI/openmixup#1]
Hi authors,
Thanks for your great work. When I run the script following your GETTING_STARTED.md, it returns me "no module named ''openmixup". When I tried to import openmixup in python directly, it tells me "no module named 'openmixup.version'". It seems that the version.py file in in the .gitignore list. Is this the reason for the error?

**Comment by Lupin1998** [comment]
Hi @xiangyu8, thanks for your attention. I am sorry for some bugs in the init version caused by refactoring the project this month. I will update a fixed version as soon as possible (within 24 hours), which will provide more configs for our classification experiments. I will continue to update more experiment configs and results in the next two months.

**Comment by xiangyu8** [comment]
Okay, thank you so much.
