### ISSUE TITLE
[Feature] Can we load ImageNet data using LMDB?

### ISSUE THREAD

**Issue by wang-tf** [Westlake-AI/openmixup#26]
### Describe the feature

Current ImageNet data loader can only support pillow, cv2 backends to load images. By some reasone, I need to use LMDB  to load dataset which is supported by mmcls.
https://github.com/Westlake-AI/openmixup/blob/8966870a05b85ea940a02c4646693ec101ab0575/openmixup/datasets/data_sources/image_list.py#L49-L51

**Comment by Lupin1998** [comment]
Hi @wang-tf, thanks for your suggestion. Since I haven't used LMDB to load image datasets, I'd like to have some exciting implementations for reference. But I can't find the support of the LMDB dataset in [MMClassification](https://github.com/open-mmlab/mmclassification). Could you please show me the source code file and its branch in the MMLab project? You can contact me directly via e-mail or WeChat (Lupin_1998). I am looking forward to having discussions with you.

**Comment by wang-tf** [comment]
In mmcls, dataset can load using [file_client_args](https://github.com/open-mmlab/mmclassification/blob/91b85bb4a5df075ae2690273da32819b298e4395/mmcls/datasets/custom.py#L163) which is supported by mmcv:

https://github.com/open-mmlab/mmcv/blob/e417035f5d473b9f85d15ba01267d48d7f30e71e/mmcv/fileio/file_client.py#L790.

So I think LMDB can be used in mmcls.

**Comment by Lupin1998** [comment]
Thanks very much for your hint. According to the [implementation](https://github.com/open-mmlab/mmclassification/blob/91b85bb4a5df075ae2690273da32819b298e4395/mmcls/datasets/custom.py) in MMClassification, I will support the same [file_client](https://github.com/open-mmlab/mmcv/blob/e417035f5d473b9f85d15ba01267d48d7f30e71e/mmcv/fileio/file_client.py) functions as the `CustomDataset` in the next commit.

**Comment by Lupin1998** [comment]
Hi, @wang-tf. We have updated `ImageList` in [image_list.py](https://github.com/Westlake-AI/openmixup/tree/main/openmixup/datasets/data_sources/image_list.py) according to MMClassification, which is used to load images from list files in the latest [commit](https://github.com/Westlake-AI/openmixup/commit/ac60a38e46f814895db6673b850fd816b2a5fac1). The LMDB dataset can be used by modifying `file_client_args` as follows.
```python
# dataset settings
data_source_cfg = dict(
    type='ImageNet',
    file_client_args=dict(backend='lmdb')),
```
Since I haven't tested it with LMDB datasets, it can be used as MMClassification. You can contact me if some bugs occur. I close this issue if there is no more question.
