### ISSUE TITLE
Normalize mean and std in tiny_imagenet

### ISSUE THREAD

**Issue by zeyuanyin** [Westlake-AI/openmixup#47]
When normalizing data in tiny_imagenet, ```mean=[0.485, 0.456, 0.406], std=[0.229, 0.224, 0.225]``` are used as mean and std, but they are designed for imagenet dataset.

Why not use tiny_imagenet's mean and std  ```mean=[0.4802, 0.4481, 0.3975], std=[0.2302, 0.2265, 0.2262]```?

https://github.com/Westlake-AI/openmixup/blob/084a8f113df34997d041c323a2ea1c9342f5400d/configs/classification/_base_/datasets/tiny_imagenet/sz64_bs100.py#L10-L20

**Comment by Lupin1998** [comment]
Hi, @zeyuanyin. Thanks for raising this question. In OpenMixup, we only adopt two sets of mean and std, i.e., using the mean and std of ImageNet for all image datasets except for using those statistics of CIFAR-100 for CIFAR-10/100. As you know, it is better to use the local mean and std calculated on each dataset to achieve normalization preprocess. However, we consider using the ImageNet statistics for three reasons:
* Except for CIFAR-10/100, the commonly used image classification datasets share similar normalization statistics (the means and stds) and input resolutions as ImageNet-1k. For example, the supported fine-grained datasets usually contain some parts of ImageNet (e.g., CUB-200 and StandfoldCars). As for datasets with smaller resolutions than ImageNet, e.g., STL-10 (96x96x3) and Tiny-ImageNet (64x64x3), they are subsets of ImageNet and can apply the ImageNet statistics.
* Using the mean and std to perform normalization matters while applying which statistics have negligible effects on the performance. For example, some projects of Google Research (e.g., EfficientNet) use the mean and std of `[0.5, 0.5, 0.5]` on ImageNet, which also achieves high performance.
* Since transfer learning is a common practice in OpenMixup, applying the same normalization statistics during self-supervised pre-training or supervised training is convenient for conducting transfer experiments.

Overall, we choose to use the mean and std of ImageNet-1k to normalize the input images from Tiny-ImageNet instead of using Tiny-ImageNet's statistics. I hope these reasons will solve your doubts.

**Comment by zeyuanyin** [comment]
Many thanks for your detailed answers.
