### ISSUE TITLE
Training Vision transformer for CIFAR-10 with TransMix augmentation

### ISSUE THREAD

**Issue by khawar-islam** [Westlake-AI/openmixup#49]
Dear @LirongWu 

How I can train vision transformer on CIFAR-10 dataset with TransMix augmentation? I have followed your GitHub issue and trained automix on cifar100

` PORT=29001 bash tools/dist_train.sh configs/classification/cifar100/automix/basic/r18_l2_a2_near_L1_01_mlr5e_2.py 1
`

**Comment by Lupin1998** [comment]
Hi, @khawar-islam, thanks for using OpenMixup. We add config files of Vision Transformers on the CIFAR-100 dataset, and you can train TransMix with [deit_s_transmix_sz224_bs100_ep200](https://github.com/Westlake-AI/openmixup/blob/main/configs/classification/cifar100/mixups/vits/deit_small/deit_s_transmix_sz224_bs100_ep200.py). Since the CIFAR-10 dataset is too simple to evaluate various network architectures and Mixup augmentations, we plan to conduct small-scale experiments on CIFAR-100. If you want to train TransMix with ViTs on CIFAR-10, you can get the config file by modifying the config for the CIFAR-100 dataset. As for the benchmark results of ViTs and Mixups on CIFAR-100, we will update them in the future.

**Comment by Lupin1998** [comment]
If there is no more question, I will close this issue. Please watch us for the update of config files and benchmark results on CIFAR-100 with ViT backbones. Feel free to open a new issue when a new question occurs.
