### ISSUE TITLE
Network name issues

### ISSUE THREAD

**Issue by xiaobaitubaibaibai** [Westlake-AI/openmixup#54]
Dear author ,Since the Moganet network also has a residual structure, can I call this network residual network?

**Comment by Lupin1998** [comment]
Thanks for your question @xiaobaitubaibaibai, and I agree with your comment. Since ResNet was proposed, the most modern architectures all adopt the residual network.

**Comment by xiaobaitubaibaibai** [comment]
Thank you for your reply!Thank you!

**Comment by xiaobaitubaibaibai** [comment]
> Thanks for your question @xiaobaitubaibaibai, and I agree with your comment. Since ResNet was proposed, the most modern architectures all adopt the residual network.

Dear author,I have another question:in the article ,do Moganet_tiny belong to deep neural networks?If not,which networks are deep networks?

**Comment by Lupin1998** [comment]
Hi, @xiaobaitubaibaibai, sorry for the late reply. MogaNet-Tiny belongs to deep neural networks since it requires deep stacks of many network blocks despite its small parameter sizes. On the contrary, you can regard [VanillaNet](http://arxiv.org/abs/2305.12972) variants as shallow networks. I will close this issue if there are no more questions.
